;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        evil-append
        evil-append-line
        evil-backward-char
        evil-delete
        evil-delete-char
        evil-emacs-state
        evil-escape-emacs-state
        evil-escape-insert-state
        evil-exit-emacs-state
        evil-exit-visual-state
        evil-forward-char
        evil-insert
        evil-next-line
        evil-next-visual-line
        evil-normal-state
        evil-previous-line
        evil-previous-visual-line
        evil-substitute
        forward-sentence
        hungry-delete-backward
        hungry-delete-forward
        kill-sentence
        lispy-delete-backward
        lispy-move-beginning-of-line
        lispy-move-end-of-line
        lispy-space
        mwim-beginning-of-code-or-line
        mwim-end-of-line-or-code
        org-self-insert-command
        orgtbl-hijacker-command-109
        sis--prefix-override-handler
        skk-delete-backward-char
        skk-insert
        sp-backward-delete-char
        sp-delete-char
        sp-remove-active-pair-overlay
        spacemacs/backward-kill-word-or-region
        spacemacs/smart-move-beginning-of-line
        undo-tree-visualize
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        end-of-buffer
        evil-paste-pop
        evil-scroll-page-down
        idiig/my-mc-mark-next-like-this
        ))
